from __future__ import annotations

from enum import StrEnum


class WorkflowStatus(StrEnum):
    CREATED = "CREATED"
    INITIALIZING = "INITIALIZING"
    UNDERSTANDING = "UNDERSTANDING"
    COLLECTING_CONTEXT = "COLLECTING_CONTEXT"
    BUILDING_ERC = "BUILDING_ERC"
    VALIDATING_CONTEXT = "VALIDATING_CONTEXT"
    REASONING = "REASONING"
    EXECUTING_TOOL = "EXECUTING_TOOL"
    VALIDATING_RESULT = "VALIDATING_RESULT"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    WAITING_FOR_HUMAN = "WAITING_FOR_HUMAN"
    WAITING_FOR_EXTERNAL_EVENT = "WAITING_FOR_EXTERNAL_EVENT"
    RESUMING = "RESUMING"
    COMPLETING = "COMPLETING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class WaitingType(StrEnum):
    WAITING_FOR_USER = "WAITING_FOR_USER"
    WAITING_FOR_HUMAN = "WAITING_FOR_HUMAN"
    WAITING_FOR_EXTERNAL_EVENT = "WAITING_FOR_EXTERNAL_EVENT"
    WAITING_FOR_DEPENDENCY = "WAITING_FOR_DEPENDENCY"


class HilStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUESTED = "REQUESTED"
    WAITING = "WAITING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
