from __future__ import annotations

from enum import StrEnum


class AgentRunStatus(StrEnum):
    CREATED = "CREATED"
    INITIALIZING = "INITIALIZING"
    EXECUTING = "EXECUTING"
    WAITING_FOR_TOOL = "WAITING_FOR_TOOL"
    WAITING_FOR_RAG = "WAITING_FOR_RAG"
    WAITING_FOR_SLM = "WAITING_FOR_SLM"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    WAITING_FOR_HUMAN = "WAITING_FOR_HUMAN"
    WAITING_FOR_EVENT = "WAITING_FOR_EVENT"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
